apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api-deployment
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      components: backend
  template:
    metadata:
      labels:
        components: backend
    spec:
      containers:
        - name: conv-api
          image: antonlarichev/conv-api:1.0
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "256Mi"
              cpu: "256m"
          env:
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: conv-secrets
                  key: AMQP_USER
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: conv-secrets
                  key: AMQP_PASSWORD
            - name: AMQP_HOSTNAME
              value: rabbitmq-clusterip
            - name: AMQP_EXCHANGE
              value: exchanger
            
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: conv-secrets
                  key: RABBITMQ_URL

          volumeMounts:
            - name: uploads-volume
              mountPath: /opt/app/uploads

      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: uploads-pvc


      

# DATABASE_URL
# postgres://user:password@url:5432/db
# postgresql://demo:demo@postgres-clusterip:5432/demo

# RABBIT_URL
# amqp://username:password@host:port
# amqp://demo:demo@rabbitmq-clusterip:5672