apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: homework
spec:
  storageClassName: "local-path"
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce