apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-clusterip
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ Values.app.port }}
      protocol: TCP
  selector:
    components: {{ .Values.app.components }}