apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      components: {{ .Values.app.components }}
  template:
    metadata:
      labels:
        components: {{ .Values.app.components }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image }}:{{ .Values.app.version }}"
          ports:
            - containerPort: {{ Values.app.port }}
          resources:
            limits: {{ .Values.app.limits | toYaml | nindent 14 }}
          env: 
            - name: VITE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: {{ .Values.configmap.key }}

      
      volumes:
        - name: {{ .Values.configmap.name }}
          configMap:
            name: {{ .Values.configmap.name }}
