apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
  labels:
    name: {{ .Values.ingress.name }}
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.app.name }}-clusterip
            port: 
              number: {{ .Values.app.port }}
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: conv-api-clusterip
            port: 
              number: 3000
      - pathType: Prefix
        path: "/uploads"
        backend:
          service:
            name: conv-api-clusterip
            port:
              number: 3000
